{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "http-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-api.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "http-api.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "http-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
